-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointments
(
    id bigserial NOT NULL,
    patient_id bigint NOT NULL,
    insurance_id bigint,
    appointment_type appointment_type_enum NOT NULL,
    status status_enum NOT NULL DEFAULT 'MARCADO'::status_enum,
    starts_at timestamp without time zone NOT NULL,
    value_amount numeric(10, 2),
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.insurances
(
    id bigserial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    ans_code character varying(30) COLLATE pg_catalog."default",
    pay_day smallint,
    phone character varying(30) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    site character varying(200) COLLATE pg_catalog."default",
    ch_value numeric(10, 2),
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT insurances_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    id bigserial NOT NULL,
    full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    social_name character varying(150) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    birth_date date,
    profession character varying(100) COLLATE pg_catalog."default",
    marital_status character varying(30) COLLATE pg_catalog."default",
    nationality character varying(60) COLLATE pg_catalog."default",
    cpf character varying(14) COLLATE pg_catalog."default",
    insurance_id bigint,
    insurance_card character varying(60) COLLATE pg_catalog."default",
    cep character varying(12) COLLATE pg_catalog."default",
    address_street character varying(150) COLLATE pg_catalog."default",
    address_number character varying(20) COLLATE pg_catalog."default",
    address_comp character varying(80) COLLATE pg_catalog."default",
    address_district character varying(80) COLLATE pg_catalog."default",
    address_state character varying(60) COLLATE pg_catalog."default",
    address_country character varying(60) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    phone_mobile character varying(25) COLLATE pg_catalog."default",
    phone_landline character varying(25) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    address_city character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT patients_pkey PRIMARY KEY (id),
    CONSTRAINT patients_cpf_key UNIQUE (cpf)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_insurance_id_fkey FOREIGN KEY (insurance_id)
    REFERENCES public.insurances (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_appointments_patient
    ON public.appointments(patient_id);


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT patients_insurance_id_fkey FOREIGN KEY (insurance_id)
    REFERENCES public.insurances (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;